### ISSUE TITLE
Aim assist is broken (2) 

### ISSUE THREAD

**Issue by Di0so** [BrettRyland/BDArmory#485] opened 2023-02-28 16:32 UTC
I am currently using the latest version, and I have noticed that the aim assist is completely broken and the calculations are way off target

Spawn 2 planes with BDa AI, then use a gun, lock the target with radar, and see

It will lend out wrong calculations ( guns, rockets )

![Kerbal Space Program Screenshot 2023 02 28 - 20 25 25 31](https://user-images.githubusercontent.com/89231035/221916614-ca816125-d88a-418b-be40-62c4685c1675.png)

[KSP.log](https://github.com/BrettRyland/BDArmory/files/10852592/KSP.log)

( USING LATEST VERSION )

**Comment by BrettRyland** [comment] 2023-02-28 23:26
OK, I see the issue and can reproduce it locally, so I should be able to fix it.
This appears to be due to the target position information from the radar being overwritten when manually aiming with a fixed weapon. Turrets appear unaffected.

Btw, it would have been better to continue issue #481 instead of creating a new one.

**Comment by Di0so** [comment] 2023-03-01 04:48
alright, would really appreciate it if it gets fixed

**Comment by Di0so** [comment] 2023-03-08 06:15
Hello, I have installed the newest update, it is still broken unfortunately 
![Kerbal Space Program Screenshot 2023 03 08 - 10 13 01 35](https://user-images.githubusercontent.com/89231035/223633975-06a08170-b1a1-419e-8552-ddaaed78314d.png)
![Kerbal Space Program Screenshot 2023 03 08 - 10 12 55 10](https://user-images.githubusercontent.com/89231035/223633983-5cf40d47-c6cc-
[KSP.log](https://github.com/BrettRyland/BDArmory/files/10917717/KSP.log)
4803-be57-6b5d41462b14.png)

**Comment by BrettRyland** [comment] 2023-03-08 10:35
In what way is it not working? The indicator looks to be correct in the above image, i.e.,
![Screenshot_20230308_112330](https://user-images.githubusercontent.com/18440126/223690193-6943cde4-b607-4f56-938a-a80cb2e6cb4c.png)

**Comment by Di0so** [comment] 2023-03-09 06:13
It's supposed to be like this, this is at version 1.5.4, and it works absolutely fine 
![Kerbal Space Program Screenshot 2023 03 09 - 10 10 51 19](https://user-images.githubusercontent.com/89231035/223935739-e1e23acb-33d8-4247-9fa8-839664f85a2f.png)

**Comment by BrettRyland** [comment] 2023-03-09 10:37
> It's supposed to be like this, this is at version 1.5.4, and it works absolutely fine

No, that's using the same incorrect calculations for the reticle position as in your initial screenshot, for which the targeting reticle (the green circle) only coincides with the target's position under certain conditions.

The fixed aim assist indicator is giving you a targeting reticle in the direction to aim your guns in order to hit the target and showing your current deviation from this. I have noticed a small issue with it's position due to KSP's floating origin, which will be fixed in the next release.

**Comment by Di0so** [comment] 2023-03-17 03:31
sorry for the late reply. could you please demonstrate it to me on how you aim it?

**Comment by BrettRyland** [comment] 2023-03-17 12:04
This is how it's intended to be used https://youtu.be/ZKZ83s3G3j4.
The green dot shows where the guns are currently pointing, the targeting reticle is where you want to aim to hit the target (this is the spot the AI aims for) and the green line shows the offset between them (I think I was actually beyond the range of the guns early in the video, which is why the bullets failed to hit initially, also my not-so-great aiming...).

**Comment by Di0so** [comment] 2023-03-17 12:07
Amazing! really happy now, thank you so much

**Closed** 2023-03-17 12:17 UTC
