### ISSUE TITLE
TweakScale FATAL error. Version 1.6.1.0. Typhoon duplicated properies

### ISSUE THREAD

**Issue by Karys0** [BrettRyland/BDArmory#516] opened 2023-05-14 14:32 UTC
**Describe the bug**
Typhoon engine still has duplicated properties in tweakscale, causing a FATAL error. Even thought I have installed on CKAN v1.6.1.0 (released on 08.05.2023) and even thought in [changelog ](https://forum.kerbalspaceprogram.com/index.php?/topic/209092-19x-112x-bdarmory-plus-bda-v1610-2023-05-08/#:~:text=Changelog-,v1.6.1.0,Fix%20TweakScale%20config%20for%20Typhoon%20engine.,-Reduce%20min%20size) there is claimed that this has been fixed it isn't. Similar person has the same [issue](https://forum.kerbalspaceprogram.com/index.php?/topic/192216-tweakscale-companion-program-202303284/page/9/#comment-4282401).

**To Reproduce**
This issue occurs when I launch KSP and have BDArmory installed at the same time with tweakscale. 

**Expected behaviour**
I expected that game (After installing the newest 1.6.1.0 version) will not have that issue.

**Logs**
[KSP.log](https://github.com/BrettRyland/BDArmory/files/11472174/KSP.log)
[KSP_x64.gc.log](https://github.com/BrettRyland/BDArmory/files/11472175/KSP_x64.gc.log)
Directory C:\Program Files\Epic Games\KerbalSpaceProgram\English
[LOG 15:35:23.857] [TweakScale] ERROR: **FATAL** Part BDA.EJ200 (TFJ-EJ200 "Typhoon" Afterburning Turbofan) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0

**Screenshots**
![Kerbal Space Program Screenshot 2023 05 14 - 16 28 32 29](https://github.com/BrettRyland/BDArmory/assets/112759954/a531b7e8-0fb1-494e-a693-6e128ca11dd6)

**Additional context**
I have signed this problem also [here](https://github.com/TweakScale/TweakScale/discussions/301) . 

Me and other person got the same issue, and also the BDArmory and Ksp recall are only mods we have in common. It can't be KSP recall so it's BDArmory who causes the fatal error I think.

**Comment by BrettRyland** [comment] 2023-05-14 14:44
Yes, this is known about already. One of the other devs says it should be an easy fix, so it should be fixed in the next release. As a temporary solution, you can remove the file `GameData/BDArmory/Parts/EJ200/caesar_hone_60_TS.cfg`, which was intended to make the mass of that engine scale more consistently with other engines, which is the cause of the problem.

**Closed** 2023-05-27 10:24 UTC
