### ISSUE TITLE
Competition not starting

### ISSUE THREAD

**Issue by BenAran** [BrettRyland/BDArmory#257] opened 2021-09-16 19:18 UTC
Hello. 
After Legodlak gave me his gun calibrator plane, every time I start a competition, only the newest loaded plane activates its autopilot and takes off. If I manually activate the other ones autopilot via the vesselswitcher, the competition is also cancelled and I have to activate guardmode for both to even get fighting started.

**To Reproduce**
On the newest version of BDA (1.9.4 I think), try starting a competition. For me, it does not work for any planes on any saves anymore.

**Additional context**
No updates or additional mods were installed prior to this behavior.
PC was not turned off. (And no, restarting does not fix it)
Game has been reinstalled from the ground up, all mods have been removed through CKAN and manually.
Trying it on a different save also does not work.
Removed everything but BDA, issue still not fixed.
The plane that is originally commanded is the one that functions properly (as in you click on it and select "Fly" from the options when just looking over the facilities of the KSC)

Only thing I have not done yet is reinstalling windows entirely.
[MMPatch.log](https://github.com/BrettRyland/BDArmory/files/7180385/MMPatch.log)
[ModuleManager.log](https://github.com/BrettRyland/BDArmory/files/7180387/ModuleManager.log)

**Comment by BrettRyland** [comment] 2021-09-16 19:42
Hi,
This is fixed in dev and will be in the next bugfix release (which should be out shortly). It's caused by the mutator game mode, which defaulted to being enabled, with an empty list of mutators selected. You can fix it by either disabling the mutator game mode or selecting a few mutators if you want to play with that.
Sorry for the inconvenience.

**Comment by BenAran** [comment] 2021-09-16 19:48
Hey, thanks for telling me this.
I will give that a shot right this instance.
Oh my god it works. Thank you so much.

**Closed** 2021-09-16 20:07 UTC
