### ISSUE TITLE
Parts are not showing up in VAB or R&D.

### ISSUE THREAD

**Issue by Atomhype** [BrettRyland/BDArmory#442] opened 2022-10-24 16:52 UTC
**Describe the bug**
I installed Bd armory plus from ckan and tried everything to make it work. The only part that shows up is a cockpit.

**To Reproduce**
1.Install mod
2.Run the game with all my other mods.
3.no parts in VAB

**Logs**
[KSP.log](https://github.com/BrettRyland/BDArmory/files/9853642/KSP.log)

**Screenshots**
![VAB](https://user-images.githubusercontent.com/116585332/197581722-8680f66d-8cf1-48af-af01-2d22ad71f4bf.png)

**My Mod List**
[Mod List.txt](https://github.com/BrettRyland/BDArmory/files/9853666/Mod.List.txt)

**Comment by BrettRyland** [comment] 2022-10-24 19:44
Most likely, your tech level is too low. Many BDA+ parts require `precisionEngineering` or `composites`, others require `advAerodynamics`, `fieldScience`, `supersonicFlight` or `generalConstruction`.

**Comment by BrettRyland** [comment] 2022-11-25 21:50
Closing due to no further responses / not a bug.

**Closed by BrettRyland** 2022-11-25 21:50 UTC
