### ISSUE TITLE
B9 Procedural Wings with TU changes P-wing Textures After Reverting to Launch when BDA is Installed

### ISSUE THREAD

**Issue by VostokV5** [BrettRyland/BDArmory#380] opened 2022-07-18 14:39 UTC
**Describe the bug**
B9 Procedural Wings with Textures Unlimited changes the textures of the leading edge, trailing edge, and section of the P-wing when BDA is installed.

**Mods Installed**

- B9 Aerospace Procedural Wings Fork 0.43.0.11
- BDArmory for Runway Project 1.4.18.4
- Module Manager 4.2.2
- Textures Unlimited 1.5.10.25

**To Reproduce**
1. Make a craft with B9 Procedural Wings
2. Recolor the main parts of each section of the P-wing
3. Launch 
4. Revert to launch and then the bug should appear

**Expected behaviour**
I expected no changes in the textures of the P-wing in any situation

**Logs**
[Player.log](https://github.com/shadowmage45/TexturesUnlimited/files/9132554/Player.log)

**Screenshots**
[VIDEO OF REPRODUCTION](https://youtu.be/6a2Na50aeIs)

**Additional context**
Also works with the other B9 P-wings (Control surface and All-moving); Same thing, every section except the actual surface goes back to its original texture.

**Comment by BrettRyland** [comment] 2022-07-18 17:59
I'm unable to reproduce this locally with the same mods installed.

However, a difference I find in the KSP.log file is
```
[LOG 19:30:34.935] enabling TSMD..surface (UnityEngine.Transform) updateMode: False
[LOG 19:30:34.936] enabling TSMD..section (UnityEngine.Transform) updateMode: False
[LOG 19:30:34.936] enabling TSMD..model (UnityEngine.Transform) updateMode: False
[LOG 19:30:34.937] enabling TSMD..model (UnityEngine.Transform) updateMode: False
[LOG 19:30:34.943] enabling TSMD..surface (UnityEngine.Transform) updateMode: False
[LOG 19:30:34.943] enabling TSMD..section (UnityEngine.Transform) updateMode: False
[LOG 19:30:34.944] enabling TSMD..model (UnityEngine.Transform) updateMode: False
[LOG 19:30:34.945] enabling TSMD..model (UnityEngine.Transform) updateMode: False
```
in my log (both when loading cleanly into flight mode and when reverting to launch) vs
```
[Part]: PartModule indexing mismatch at B9.Aero.Wing.Procedural.TypeA, index 3.
Node 'SSTURecolorGUI' found in loaded data, but 'ModuleSelfSealingTank' is defined in prefab.
Looking for SSTURecolorGUI in other indices... 
...SSTURecolorGUI module found at index 4. 
[Part]: PartModule indexing mismatch at B9.Aero.Wing.Procedural.TypeA, index 4.
Node 'KSPTextureSwitch' found in loaded data, but 'SSTURecolorGUI' is defined in prefab.
Looking for KSPTextureSwitch in other indices... 
...KSPTextureSwitch module found at index 5. 
enabling TSMD..surface (UnityEngine.Transform) updateMode: False 
[Part]: PartModule indexing mismatch at B9.Aero.Wing.Procedural.TypeA, index 3.
Node 'SSTURecolorGUI' found in loaded data, but 'ModuleSelfSealingTank' is defined in prefab.
Looking for SSTURecolorGUI in other indices... 
...SSTURecolorGUI module found at index 4. 
[Part]: PartModule indexing mismatch at B9.Aero.Wing.Procedural.TypeA, index 4.
Node 'KSPTextureSwitch' found in loaded data, but 'SSTURecolorGUI' is defined in prefab.
Looking for KSPTextureSwitch in other indices... 
...KSPTextureSwitch module found at index 5. 
enabling TSMD..surface (UnityEngine.Transform) updateMode: False 
enabling TSMD..model (UnityEngine.Transform) updateMode: False 
enabling TSMD..model (UnityEngine.Transform) updateMode: False 
```
in yours when reverting to launch (after filtering out some non-relevant lines).

These lines appear to come from [here](https://github.com/shadowmage45/TexturesUnlimited/blob/3d0c0b93e9e2312f90dfe26134089a0fa2fce55b/Plugin/SSTUTools/KSPShaderTools/Util/TextureSet.cs#L444) in TU when part module indexing mismatches occur (which is not uncommon), so maybe @shadowmage45 can do something about it in the [issue](https://github.com/shadowmage45/TexturesUnlimited/issues/106) you raised there.

**Comment by VostokV5** [comment] 2022-07-18 18:03
Thank you for the response! I have no idea what these words and numbers are but it's good information and is helpful nonetheless.

**Comment by BrettRyland** [comment] 2022-07-18 18:55
After a bit of experimenting, I can trigger this bug without BDArmory installed simply by reordering the modules in the craft file (in a text editor), e.g., by moving the first two `KSPTextureSwitch` modules behind the latter two on one of the proc wings I get
![Screenshot_20220718_205225](https://user-images.githubusercontent.com/18440126/179582182-12eac883-725b-428b-932f-e8470f6afb32.png)
Note that they haven't been removed from symmetry.
Any mod or MM patch that dynamically adds modules to proc wings (as BDArmory does) is going to cause this bug.

**Comment by BrettRyland** [comment] 2022-07-18 19:11
I'm closing this issue as it's an issue with Textures Unlimited, not BDArmory (BDArmory just happens to trigger it). I've linked the issue there to this one so the TU dev can reference this.

**Closed by BrettRyland** 2022-07-18 19:11 UTC
